### ISSUE TITLE
tests are failing. we need to fix them.

### ISSUE THREAD

**Issue by palewire** [datadesk/p2p-python#17]

**Comment by charlex** [comment]
This "Todo" doc provides a good clue to why `test_image_services` is failing. 

https://github.com/newsapps/p2p-python/commit/acd2f95f8a8d6786f0362fd9a37951d0ccd371fb#diff-6170c7947caf5641ea65fd04caa7d15bR185

Also, if you manually go to one of these image service api urls, it looks busted.
http://image.p2p.tribuneinteractive.com/photos/turbine/la-test-p2p-python-temp-story-0.json

**Comment by palewire** [comment]
![FML](https://media.giphy.com/media/TynqYjsIEqDrG/giphy.gif)
