### ISSUE TITLE
Expose response headers for content item search

### ISSUE THREAD

**Issue by jperezlatimes** [datadesk/p2p-python#42]
Content services returns 3 headers whenever a search is performed: 
```
X-Total-Hits
X-Next-Results-URL
X-Previous-Results-URL
```

We should return these along with the list of content element results. This will allow pagination of search results through the wrapper much easier.

```
{
  content_items: [ ... ],
  hits: 10,
  next: https://content-api.p2p.stage.trbdevclous.com/...,
  previous: https://content-api.p2p.stage.trbdevclous.com/...,
}
```

**Comment by charlex** [comment]
I've always done this by figuring out the logic on my end. Basically, I would keep offsetting a search by the number of results I've collected until CS stopped giving me results.

This seems much more reliable though; didn't know they were returning these.

What would the response of `conn.search(params)` be? Something like this maybe?

```python
search, search_meta = conn.search(params)
print search_meta
{
  "hits": 543,
  "next_url": "http://cs.url...",
  "previous_url": "http://cs.url..."
}```

**Comment by charlex** [comment]
To avoid breaking old stuff, do you think it'd be safest to make this a new function?

Like this? `conn.search_by_page(params)`

**Comment by charlex** [comment]
@jperezlatimes Does the CS team guarantee that they'll always return these?

```
X-Total-Hits
X-Next-Results-URL
X-Previous-Results-URL
```

**Comment by jperezlatimes** [comment]
Closed by: https://github.com/datadesk/p2p-python/pull/43
